version: '3.8'

services:
    go-backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        image: nilay911/go-backend:latest
        ports:
            - '8080:8080'
        environment:
            STAGE: production
            DATABASE_URL: ${DATABASE_URL}
            DATABASE_PASS: ${DATABASE_PASS}
            PORT: 8080

    ui:
        build:
            context: ./ui # Path to your frontend Dockerfile
            dockerfile: Dockerfile
        image: nilay911/ui:latest
        ports:
            - '3000:3000' # Map port 80 inside the container to port 3000 on the host
        environment:
            NODE_ENV: development
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
