name: My Deploy

on:
    push:
        branches: [master]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Deploy to Render test environment
              id: render_deploy
              uses: johnbeynon/render-deploy-action@v0.0.8
              with:
                  service-id: ${{ secrets.RENDER_SERVICE_ID }}
                  api-key: ${{ secrets.RENDER_API_KEY }}
                  wait-for-success: true

            - name: Install jq
              run: sudo apt-get install -y jq

            - name: Fetch Render Deployment Logs
              if: steps.render_deploy.outcome == 'success'
              env:
                  RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
                  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
              run: |
                  # Get the latest deployment ID
                  DEPLOY_ID=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
                  "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" | jq -r '.[0].id')

                  # Fetch and display the logs
                  logs=$(curl -s -H "Authorization: Bearer $RENDER_API_KEY" \
                  "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys/$DEPLOY_ID/logs")
                  echo "$logs"
